### ISSUE TITLE
ENTREVISTA GESTION DE PROYECTOS

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-m#2]
[Entrevista_gestor_de_proyectos_de_software.pdf](https://github.com/user-attachments/files/16841195/Entrevista_gestor_de_proyectos_de_software.pdf)

**Comment by ToniDepp** [comment]
**Preparación:** En base al reporte plantean información bastante interesante para el desenvolvimiento de las personas involucradas 25/25.
**Conocimiento Ganado:** Concluyen de una buena manera, habiendo recopilado información que es del interés popular. 25/25. 
**Informe:** Presentan lo necesario, adjuntan evidencias y mantienen el tema central. 25/25.
**Redacción:** Recopilan buena información y facilitan la comprensión al lector. 25/25.
**Calificación:** 100/100 = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
